services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      USER_SERVICE_DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      LEGACY_SHOP_DB_PASSWORD: ${LEGACY_SHOP_DB_PASSWORD}
      ORDER_SERVICE_DB_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  gateway:
    image: ${ECR_REGISTRY}/e-commerce-gateway:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - php-legacy
      - order-service
      - cart-service

  user-service:
    image: ${ECR_REGISTRY}/e-commerce-user-service:latest
    environment:
      DB_USERNAME: ${USER_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  php-legacy:
    image: ${ECR_REGISTRY}/e-commerce-php-legacy:latest
    environment:
      DB_HOST: mysql
      DB_NAME: legacy_shop
      DB_USERNAME: legacy_shop_service
      DB_PASSWORD: ${LEGACY_SHOP_DB_PASSWORD}
    ports:
      - "8090:80"
    depends_on:
      mysql:
        condition: service_healthy

  order-service:
    image: ${ECR_REGISTRY}/e-commerce-order-service:latest
    environment:
      DB_USERNAME: ${ORDER_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  cart-service:
    image: ${ECR_REGISTRY}/e-commerce-cart-service:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8082:8082"
    depends_on:
      redis:
        condition: service_healthy


volumes:
  mysql-data:
  redis-data: