apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: e-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: SecretStore
  target:
    name: db-credentials
  dataFrom:
    - find:
        path: /e-commerce/prod/
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "/e-commerce/prod/(.*)"
            target: "$1"