apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-ssm
  namespace: e-commerce
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa