server:
  port: 8084

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@localhost:27017/review_db?authSource=admin}

order:
  base-url: ${ORDER_BASE_URL:http://order-service:8081}