server:
  port: 8084

spring:
  application:
    name: review-service

aws:
  s3:
    review-bucket: e-commerce-review-images-sungmin2026
    region: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}